### PR TITLE
docs: update jekyll-theme-yat regularly

### PR DESCRIPTION
**Pull request by jeffreytse**
Regularly update information.

### CODE REVIEW

**Comment by geraldb** [comment]
@jeffreytse  Thanks for all the updates.  You are more than welcome to join the planet jekyll github org here than you can update in the future (without pull requests) - let me know if you are interested and I send you the invite via github (if you are interested and  accept you will see the invite also on top of the jekyll github org page).   Happy new year! Prosit 2021!  Keep it up. Cheers.

**Comment by jeffreytse** [comment]
Hi @geraldb 

Ok, you send me the invite, I'll join the org. Happy new year! Prosit 2021! Keep it up. Cheers.

Thanks and regards

**Comment by geraldb** [comment]
Welcome. You should see the invite now on top of the page if you go to <https://github.com/planetjekyll>  and I think GitHub also sends out an email.  Thanks again for the updates. Keep it up. Cheers. Prost.

**Comment by jeffreytse** [comment]
Yes. I already saw it and joined.

**Pull request merged**
